
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
      repositories:
        enabled: false
    neo4j:
      #open-in-view: false
      uri: bolt://localhost:7687
      username: neo4j
      password: admin
      driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
      repositories:
        enabled: false
#    mongodb:
#      database: config
#      host: localhost
#      port: 27017
#      username: root
#      password: 514840279@qq.com
#      option: 
#        min-connection-per-host: 0
#        max-connection-per-host: 100
#        threads-allowed-to-block-for-connection-multiplier: 5
#        server-selection-timeout: 30000
#        max-wait-time: 120000
#        max-connection-idle-time: 0
#        max-connection-life-time: 0
#        connect-timeout: 10000
#        socket-timeout: 0
#        socket-keep-alive: false
#        ssl-enabled: false
#        ssl-invalid-host-name-allowed: false
#        always-use-m-beans: false
#        heartbeat-socket-timeout: 20000
#        heartbeat-connect-timeout: 20000
#        min-heartbeat-frequency: 500
#        heartbeat-frequency: 10000
#        local-threshold: 15
        
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 514840279@qq.com
    url: jdbc:mysql:///application?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: root
    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true
        useServerPrepStmts: true
        
  mail:
    host: smtp.qq.com
    username: 514840279
    password: getbvsdrwniebiaj
    from: 514840279@qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            required: true


phone:
  accessKeyId: yourAccessKeyId
  accessKeySecret: yourAccessKeySecret
  signName: 云通信
  templateCode: SMS_1000000
  # 此处的模板中 'order' 对应阿里云短信模板中设置的${order}
  # {order_title} 对应系统替换的关键词
  # 此处代码无需修改 仅需在模板中需要出现的位置填写 ${order}或 ${username}
  templateParam: '{"order":{order_title},"username":{username}}'
  

# 自定义管理查询的 es 名称
elasticsearch:
  index:
    name: 标讯数据5
    type: text    
    amount: 中标金额数值
    