server:
  port: 80
  tomcat:    uri-encoding: utf-8
#  ssl:#    key-store: classpath:danyuan.keystore
#    key-password: danyuan
#    key-store-type: JKS
#    key-alias: DY
#    enabled: true
#  ssl:#    key-store: classpath:danyuan.p12
#    key-password: danyuan
#    key-store-type: PKCS12
#    key-alias: 1
#

spring:
  profiles:    active:    - localhost
  resources:    static-locations:    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:./resume/
    - file:./outputfile/
    - file:./uploadfile/
    - file:./headimg/
    - file:./file/
    - file:./markdown/
    - file:./source/
  aop:
    proxy-target-class: true
  datasource:
    
    hikari:      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 18000000
      connection-test-query: SELECT 1 from dual
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: ORACLE
    open-in-view: false
    hibernate:
      ddl-auto: update
      show_sql: true
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  session:
    store-type: none
  thymeleaf:
    servlet:      content-type: text/html
    encoding: UTF-8
    cache: false
    mode: HTML
    
  main:
    banner-mode: console
    web-application-type: servlet
    allow-bean-definition-overriding: true
    

  
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.danyuan.application: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  file: log.log
  pattern:
    level: info
    #console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH24mmss} === [%thread] === %-5level === %logger{50} ==== %msg%n"
