
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
      repositories:
        enabled: false
    neo4j:
      #open-in-view: false
      uri: bolt://localhost:7687
      username: neo4j
      password: admin
      repositories:
        enabled: false

  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 514840279@qq.com
    url: jdbc:mysql:///application?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: root
    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true
        useServerPrepStmts: true
        
  mail:
    host: smtp.qq.com
    username: 514840279
    password: getbvsdrwniebiaj
    from: 514840279@qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            required: true


phone:
  accessKeyId: yourAccessKeyId
  accessKeySecret: yourAccessKeySecret
  signName: 云通信
  templateCode: SMS_1000000
  # 此处的模板中 'order' 对应阿里云短信模板中设置的${order}
  # {order_title} 对应系统替换的关键词
  # 此处代码无需修改 仅需在模板中需要出现的位置填写 ${order}或 ${username}
  templateParam: '{"order":{order_title},"username":{username}}'
  
user:
  #结果分析表名称
  table:
    base: bids_bx_基本信息_v3
    pingbiao: bids_bx_评标专家_v3
    zhongbiao: bids_bx_中标信息_v3
  file:
    outputfile: outputfile

# 自定义管理查询的 es 名称
elasticsearch:
  index:
    name: 标讯数据5
    type: text    
    amount: 中标金额数值
    