server:
  port: 80
  tomcat:    uri-encoding: utf-8
#  ssl:#    key-store: classpath:danyuan.keystore
#    key-password: danyuan
#    key-store-type: JKS
#    key-alias: DY
#    enabled: true
#  ssl:#    key-store: classpath:danyuan.p12
#    key-password: danyuan
#    key-store-type: PKCS12
#    key-alias: 1
#

spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300      repositories:        enabled: false
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: admin
      repositories:
        enabled: false
  aop:
    proxy-target-class: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    password: 514840279@qq.com
    url: jdbc:mysql:///application?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: root
    hikari:      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 1800
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
    
  mail:
    host: smtp.qq.com
    username: 514840279
    password: nepfflumbfbicajd
    from: 514840279@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  session:
    store-type: none
  thymeleaf:
    servlet:      content-type: text/html
    encoding: UTF-8
    mode: HTML5
  main:
    banner-mode: console
    web-application-type: servlet
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    org.danyuan: DEBUG
phone:
  accessKeyId: yourAccessKeyId
  accessKeySecret: yourAccessKeySecret
  signName: 云通信
  templateCode: SMS_1000000
  # 此处的模板中 'order' 对应阿里云短信模板中设置的${order}
  # {order_title} 对应系统替换的关键词
  # 此处代码无需修改 仅需在模板中需要出现的位置填写 ${order}或 ${username}
  templateParam: '{"order":{order_title},"username":{username}}'
  
user:
  #结果分析表名称
  table:
    base: bids_bx_基本信息_v3
    pingbiao: bids_bx_评标专家_v3
    zhongbiao: bids_bx_中标信息_v3
  file:
    outputfile: outputfile

# 自定义管理查询的 es 名称
elasticsearch:
  index:
    name: 标讯数据5
    type: text    
    